name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports

      - name: Publish Test results
        uses: EnricoMipublish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/TEST-*.xml'

      - name: Add test status badge
        uses: stefanbuck/jekyll-auto-badge@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          readme: README.md